items:
  - url: https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Redline%20%28Field-Tested%29
    threshold_price: 10.0
  - url: https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Desert-Strike%20%28Field-Tested%29
    threshold_price: 5.0
  # Add more items here...
